FROM php:7.2.7-apache

# Install Option
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-install -j$(nproc) iconv \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install -j$(nproc) gd
RUN docker-php-ext-install pdo_mysql mysqli mbstring

# Change Header Option
COPY php.ini /usr/local/etc/php/

EXPOSE 80
